taskutil: introduce taskoptions to reduce argument numbers
introduce taskoptions to reduce argument numbers.
Otherwise, ci would be failed by:
```
Error: pkg/taskutil/taskutil.go:51:1: argument-limit:
maximum number of arguments per function exceeded; max 12 but got 13
func NewTask(ctx context.Context, client *containerd.Client,
container containerd.Container, attachStreamOpt []string,
isInteractive, isTerminal, isDetach bool, con console.Console,
logURI, detachKeys, namespace string, detachC chan<- struct{}, checkpointDir string)
```

Signed-off-by: ChengyuZhu6 <hudson@cyzhu.com>